import type { Metadata } from 'next';
import { Nunito_Sans } from 'next/font/google';
import './globals.css';

const nunitoSans = Nunito_Sans({
    subsets: ['latin'],
    variable: '--font-nunito-sans',
    weight: ['400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
    title: 'Vocare|Dashboard',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='de'>
            <body className={`${nunitoSans.className} antialiased min-h-screen`}>{children}</body>
        </html>
    );
}
